image: registry.gitlab.com/modioab/base-image/fedora-31/build:master
stages:
    - test
    - again

before_script:
    - uname -a
    - make -f build.mk login
    # PODMAN_RUNTIME defaults to BUILDAH_RUNTIME only if
    # BUILDAH_RUNTIME is set:
    - ": ${BUILDAH_RUNTIME+${PODMAN_RUNTIME=$BUILDAH_RUNTIME}}"
    # This is because PODMAN_RUNTIME needs to be unset and not empty
    # if this is to work:
    - podman ${PODMAN_RUNTIME+--runtime} ${PODMAN_RUNTIME} info

test:
    stage: test
    tags:
        - x86_64
    script:
        - make -C test test test-publish
        - make -C test temp-publish


test:container:
    stage: again
    tags:
        - x86_64
    image: registry.gitlab.com/modioab/build.mk/test-container:${CI_PIPELINE_ID}
    before_script: []
    script:
        - /usr/bin/python3 /container-script.py
