%YAML 1.1
---
default:
    image: registry.gitlab.com/modioab/base-image/fedora-${FEDORA_ROOT_RELEASE}/build:master
    tags:
        - x86_64

stages:
    - test
    - again


variables:
    FEDORA_ROOT_RELEASE: 33
    PODMAN_PULL: "--pull=false"

before_script:
    - uname -a
    - make -f build.mk login
    # PODMAN_RUNTIME falls back to BUILDAH_RUNTIME only if unset
    - ": ${PODMAN_RUNTIME=$BUILDAH_RUNTIME}"
    - podman ${PODMAN_RUNTIME:+--runtime} ${PODMAN_RUNTIME} info

test:
    stage: test
    script:
        - make -C test test test-publish
        - make -C test temp-publish


test:container:
    stage: again
    image: registry.gitlab.com/modioab/build.mk/test-container:${CI_PIPELINE_ID}
    before_script: []
    script:
        - /usr/bin/python3 /container-script.py
...
