%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
    - project: ModioAB/CI
      ref: main
      file:
          - /ci/default.yml

stages:
    - test
    - again


variables:
    PODMAN_PULL: "--pull=false"


before_script:
    - uname -a
    - make -f build.mk login
    # PODMAN_RUNTIME falls back to BUILDAH_RUNTIME only if unset
    - ": ${PODMAN_RUNTIME=$BUILDAH_RUNTIME}"
    - podman ${PODMAN_RUNTIME:+--runtime} ${PODMAN_RUNTIME} info


test:
    stage: test
    script:
        - make -C test test test-publish
        - make -C test temp-publish


test:container:
    stage: again
    image: ${CI_REGISTRY_IMAGE}/test-container:${CI_PIPELINE_ID}
    before_script: []
    script:
        - /usr/bin/python3 /container-script.py
...
