image: registry.gitlab.com/modioab/base-image:fedora-26-build-master
stages:
    - test

before_script:
    - uname -a
    - make -f build.mk login
    - "docker info ||:"
    - "podman info ||:"

test:
    stage: test
    tags:
        - docker
        - x86_64
    script:
        - make -C test test test-publish
