image: registry.gitlab.com/modioab/base-image:fedora-26-build-master
stages:
    - test

before_script:
    - uname -a

test:
    stage: test
    tags:
        - docker
        - x86_64
    script:
        - make -C test login test
